apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-rwx
  resources:
    requests:
      storage: 10Gi